Mission09_ht242/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_ht242.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_ht242.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission09_ht242/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_ht242.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_ht242.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Mission09_ht242/Views/Shared/BookSummary.cshtml
@{
}

@model Book


@*Divs are just for styling*@
<div class="card card-outline-primary m-1 p-1">
    <div class="p-1">
        <h4 class="bg-light p-1">
            @Model.Title <span class="badge bg-dark" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
        <ul class="list-unstyled">
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Number of Pages: @Model.PageCount</li>
        </ul>

    </div>

@*This form sends the bookid and current url when the user click the "Add to Cart" button*@
    <form method="post" asp-page="/Checkout">

        <input type="hidden" asp-for="@Model.BookId" />

        <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-outline-danger float-end">Add to Cart</button>
        </span>

    </form>
</div>

Mission09_ht242/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
@*Top banner*@
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOKSTORE</div>
                <div class="col-6 text-end">
                    <vc:cart-summary/>
                </div>
            </div>
        </div>
    </div>

@*This is where the body renders*@
    <div class="row m-2 p-2">

@*Uses grid to space out cards*@
        <div id="categories" class="col-2">
            <vc:types></vc:types>
        </div>

        <div class="col-7">
            @RenderBody()
        </div>

    </div>

</body>
</html>