Mission09_ht242/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_ht242.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_ht242.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Cart cart { get; set; }
        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        [HttpGet]
        public IActionResult CompleteCheckout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult CompleteCheckout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/Confirmation");
            }
            else
            {
                return View();
            }
        }
    }
}

Mission09_ht242/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission09_ht242.Infrastructure;
using Mission09_ht242.Models;

namespace Mission09_ht242.Pages
{
    public class CheckoutModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public CheckoutModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public Cart cart { get; set; }

/*Variable to hold the url the shopper was at before going to the cart*/
        public string ReturnUrl { get; set; }

/*Get method*/
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

/*Set method*/
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

/* Post method for remove button */
        public IActionResult OnPostRemove (int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Mission09_ht242/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission09_ht242.Pages
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission09_ht242/Pages/Checkout.cshtml
@page
@model Mission09_ht242.Pages.CheckoutModel
@{
}
<br /><br />
<h1 class="">Your Cart</h1>
<br />

@*Checkout table*@
<table class="table table-bordered table-striped shadow-lg">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

@*Entries are dynamically added here*@
    <tbody>
        @foreach (var i in Model.cart.Items)
        {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@(i.Book.Price.ToString("c"))</td>
            <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnURL" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-outline-danger">Remove</button>
                </form>
            </td>
        </tr>
        }
    </tbody>

@*Calculates subtotal*@
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<br />

@*Url will bring you back to where you just were*@
<div>
    <a class="btn btn-danger" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-danger" asp-controller="Purchase" asp-action="CompleteCheckout">Checkout</a>
</div>

Mission09_ht242/Pages/Confirmation.cshtml
@page
@model Mission09_ht242.Pages.ConfirmationModel
@{
}

<div class="text-center">
    <h2>Thanks for your order!</h2>
    <p>You probably won't get an email with shipping information</p>

    <a class="btn btn-danger" asp-controller="Home">Return Home</a>     
</div>

Mission09_ht242/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">BOOKSTORE</span>
    </div>
    
    <div class="m-1 p-1 row">
        <div class="col-3">

        </div>

        <div class="col-6">
            @RenderBody()
        </div>
    </div>
</body>
</html>